"""empty message

Revision ID: 9f0a5c6b3caf
Revises: 
Create Date: 2022-01-24 16:23:08.610482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f0a5c6b3caf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('_password', sa.String(length=200), nullable=False),
    sa.Column('avatar', sa.String(length=100), nullable=True, comment='头像'),
    sa.Column('signature', sa.String(length=100), nullable=True, comment='签名'),
    sa.Column('join_time', sa.DateTime(), nullable=True, comment='加入时间'),
    sa.Column('is_staff', sa.Boolean(), nullable=True, comment='是否员工'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否可用'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
